name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '27 1 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        stale-issue-message: >
          This issue has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs. Thank you
          for your contributions.
        stale-issue-label: 'Stale: Discard'
        exempt-issue-labels: 'Stale: Keep'
        days-before-issue-stale: 30
        days-before-issue-close: 5


        stale-pr-label: 'Stale: Discard'
        exempt-pr-labels: 'Stale: Keep'
        stale-pr-message: >
          This pull request has been automatically marked as stale because it
          has not had recent activity. It will be closed if no further activity
          occurs. Thank you for your contributions.
        days-before-pr-stale: 45
        days-before-pr-close: 10
        exempt-draft-pr: true
